name: My GitHub Workflow

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Debug Node.js Version
        run: echo "Node.js version: $(node -v)"

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Debug Installed Dependencies
        run: echo "Installed dependencies: $(ls node_modules)"

      - name: Run Tests
        run: |
          echo "Running tests..."
          npm test -- --verbose  # Add verbose output for debugging
